Parameters:
  Customer:
    Description: 'Customer Name'
    Type: String
    Default: 'Onica'
  Application:
    Description: 'Application Name'
    Type: String
    Default: 'PagerDuty'
  Environment:
    Description: 'Environment'
    Type: String
    Default: 'Dev'
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: !Ref Customer
          AttributeType: "S"
        -
          AttributeName: !Ref Application
          AttributeType: "S"
        -
          AttributeName: !Ref Environment
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: !Ref Customer
          KeyType: "HASH"
        -
          AttributeName: !Ref Environment
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        -
          IndexName: "GSI"
          KeySchema:
            -
              AttributeName: "TicketSales"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
